from django.urls import path
from customers import views as customer_views
#from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('', views.dashboard_view, name='admin_dashboard'),
    path('property/add/', views.add_property_view, name='add_property'),
    path('property/edit/<int:pk>/', views.edit_property_view, name='edit_property'),
    path('property/delete/<int:pk>/', views.delete_property_view, name='delete_property'),
    path('activities/all/', views.all_activities_view, name='all_activities'),
    path('lead/add/', customer_views.add_lead_view, name='add_lead'),
    path('properties/', views.property_list_view, name='property_list'),
    path('projects/', views.project_list_view, name='project_list'),
    path('project/add/', views.add_project_view, name='add_project'),
    path('project/edit/<int:pk>/', views.edit_project_view, name='edit_project'),
    path('project/delete/<int:pk>/', views.delete_project_view, name='delete_project'),
    path('leads/', views.lead_list_view, name='lead_list'),
    path('lead/edit/<int:pk>/', views.edit_lead_view, name='edit_lead'),
    path('lead/delete/<int:pk>/', views.delete_lead_view, name='delete_lead'),
    path('lead/mark-read/<int:pk>/', views.mark_enquiry_read, name='mark_enquiry_read'),
    path('lead/mark-replied/<int:pk>/', views.mark_enquiry_replied, name='mark_enquiry_replied'),
    path('customers/', views.customer_list_view, name='customer_list'),
    path('customer/add/', views.add_customer_view, name='add_customer'),
    path('customer/edit/<int:pk>/', views.edit_customer_view, name='edit_customer'),
    path('customer/delete/<int:pk>/', views.delete_customer_view, name='delete_customer'),
    path('agents/', views.agent_list_view, name='agent_list'),
    path('agent/add/', views.add_agent_view, name='add_agent'),
    path('agent/edit/<int:pk>/', views.edit_agent_view, name='edit_agent'),
    path('agent/delete/<int:pk>/', views.delete_agent_view, name='delete_agent'),
    path('payments/', views.payment_list_view, name='payment_list'),
    path('payment/add/', views.add_payment_view, name='add_payment'),
    path('payment/delete/<int:pk>/', views.delete_payment_view, name='delete_payment'),
    path('payment/status/<int:pk>/', views.update_payment_status, name='update_payment_status'),
    path('payment/edit/<int:pk>/', views.edit_payment_view, name='edit_payment'),
    path('reports/', views.reports_analytics_view, name='reports_analytics'),
    path('profile/', views.profile_view, name='admin_profile'),
    path('profile/edit/', views.profile_view, {'edit': 'true'}, name='edit_admin_profile'),
    path('settings/password/', views.change_password_view, name='admin_change_password'),
    #path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('logout/', views.logout_view, name='admin_logout'),
    path('api/fetch-notifications/', views.fetch_notifications_ajax, name='fetch_notifications_ajax'),
    path('notification/read/<int:pk>/', views.mark_notification_read, name='mark_notification_read'),
    path('mark-ajax-read/', views.mark_ajax_read, name='mark_ajax_read'),
    path('admin-dashboard/bookings/', views.admin_booking_management, name='admin_bookings'),
    path('admin-dashboard/bookings/<int:booking_id>/status/',views.update_booking_status,name='update_booking_status'),
    path('admin-dashboard/bookings/<int:booking_id>/delete/',views.delete_booking,name='delete_booking',),
    path('admin-dashboard/approve-property/<int:pk>/', views.admin_approve_property, name='admin_approve_property'),
    #path('admin-dashboard/assign-lead/<int:enquiry_id>/', views.admin_assign_lead, name='admin_assign_lead'),
    path('lead/site-visit-action/<int:pk>/<str:action>/', views.handle_visit_action_ajax, name='visit_action_ajax'),
    path('lead/site-visit-approvals/', views.site_visit_approvals_view, name='site_visit_approvals'),
    path('lead/site-visit/delete/<int:visit_id>/', views.delete_site_visit, name='delete_site_visit'),
    path('admin-dashboard/commissions/', views.admin_commission_management, name='admin_commission_management'),
    path('admin-dashboard/commission/update/<int:pk>/', views.update_commission_status, name='update_commission_status'),
    path('scheduling/',views.visit_schedule_list_view,name='visit_schedule_list'),
    path('scheduling/assign-agent/<int:schedule_id>/',views.assign_schedule_agent,name='assign_schedule_agent'),
    path('scheduling/update-date-time/<int:schedule_id>/',views.update_schedule_date_time,name='update_schedule_date_time'),
    path('scheduling/delete/<int:schedule_id>/',views.delete_visit_schedule,name='delete_visit_schedule'),

    path('agents/<int:pk>/toggle-status/', views.toggle_agent_status, name='toggle_agent_status'),

    path('agent/details/<int:pk>/', views.agent_details_ajax, name='agent_details_ajax'),

    path('blogs/', views.blog_list_view, name='blog_list'),
    path('blog/add/', views.add_blog_view, name='add_blog'),
    path('blog/edit/<int:pk>/', views.edit_blog_view, name='edit_blog'),
    path('blog/delete/<int:pk>/', views.delete_blog_view, name='delete_blog'),

]